const animals = [
  {
    id: 'red-panda',
    name: '小熊貓',
    en: 'Red Panda',
    habitat: 'forest',
    image: './public/images/red-panda.webp',
    tag: '森林攀爬高手',
    description: '小熊貓住在亞洲山地森林，擅長在樹枝間活動，主要以竹類為食。',
    facts: [
      { label: '分布', value: '喜馬拉雅山脈一帶至中國西南的森林' },
      { label: '食物', value: '竹葉為主，也會吃果實與小型動物' },
      { label: '本領', value: '靈活攀爬，長尾巴能協助平衡並保暖' },
    ],
    conservation: '棲地流失與破碎化威脅野外族群，保護森林及連通的棲地很重要。',
  },
  {
    id: 'elephant',
    name: '非洲象',
    en: 'African Elephant',
    habitat: 'savanna',
    image: './public/images/elephant.webp',
    tag: '草原巨人',
    description: '非洲象以長鼻取食、飲水和溝通，生活在草原、林地等多種環境。',
    facts: [
      { label: '分布', value: '撒哈拉以南非洲的草原、林地與森林' },
      { label: '食物', value: '草、葉片、樹皮與果實' },
      { label: '本領', value: '長鼻可嗅聞、取食、飲水，也能搬動物件' },
    ],
    conservation: '棲地縮減、象牙盜獵與人象衝突都是保育挑戰；維護棲地並降低衝突有助象群生存。',
  },
  {
    id: 'tiger',
    name: '老虎',
    en: 'Tiger',
    habitat: 'forest',
    image: './public/images/tiger.webp',
    tag: '森林頂級掠食者',
    description: '老虎是亞洲的大型貓科動物，會利用森林、草原與濕地等棲地狩獵。',
    facts: [
      { label: '分布', value: '亞洲各地的森林、草原與濕地' },
      { label: '食物', value: '以鹿、野豬等中大型哺乳動物為主' },
      { label: '特徵', value: '每隻老虎的條紋排列都不相同' },
    ],
    conservation: '棲地流失與破碎化、獵捕及獵物減少威脅老虎；連結棲地並防止盜獵是保育重點。',
  },
  {
    id: 'giraffe',
    name: '長頸鹿',
    en: 'Giraffe',
    habitat: 'savanna',
    image: './public/images/giraffe.webp',
    tag: '草原高個子',
    description: '長頸鹿以高大的身形和斑紋聞名，常在非洲稀樹草原的樹冠間覓食。',
    facts: [
      { label: '分布', value: '非洲的稀樹草原與開闊林地' },
      { label: '食物', value: '以金合歡等樹木的葉片為主' },
      { label: '本領', value: '長舌和高大的身形能幫助牠取食高處的葉子' },
    ],
    conservation: '棲地轉變與破碎化、偷獵等壓力影響部分族群；保護草原和林地有助長頸鹿生存。',
  },
  {
    id: 'penguin',
    name: '企鵝',
    en: 'Penguin',
    habitat: 'polar',
    image: './public/images/penguin.webp',
    tag: '海中飛行家',
    description: '企鵝是不會飛的海鳥，以像鰭的翅膀在水中快速游泳。',
    facts: [
      { label: '分布', value: '多數生活在南半球，並非所有企鵝都住在南極' },
      { label: '食物', value: '魚、磷蝦與其他小型海洋動物' },
      { label: '本領', value: '翅膀演化成鰭狀，適合在海中推進' },
    ],
    conservation: '氣候變遷、漁業活動與海洋污染會影響部分企鵝族群；保護海洋和繁殖地有助牠們存續。',
  },
  {
    id: 'sloth',
    name: '樹懶',
    en: 'Sloth',
    habitat: 'forest',
    image: './public/images/sloth.webp',
    tag: '樹梢慢行者',
    description: '樹懶長時間待在中南美洲的樹冠層，以緩慢的動作節省能量。',
    facts: [
      { label: '分布', value: '中南美洲的熱帶森林' },
      { label: '食物', value: '以樹葉為主，依種類也會吃嫩芽或果實' },
      { label: '本領', value: '長爪能牢牢抓住樹枝，緩慢代謝有助節省能量' },
    ],
    conservation: '森林砍伐與棲地破碎化使樹懶失去棲身之所；保護連續的森林棲地很重要。',
  },
];

const habitats = [
  {
    id: 'forest',
    name: '森林',
    en: 'Forest',
    image: './public/images/forest-hero.webp',
    description: '從溫帶林到熱帶雨林，層層樹冠提供食物、遮蔽與多樣的棲身空間。',
  },
  {
    id: 'savanna',
    name: '稀樹草原',
    en: 'Savanna',
    image: './public/images/savanna.webp',
    description: '草地、散生樹木與季節性降雨交織而成，是非洲大型草食動物的重要家園。',
  },
  {
    id: 'polar',
    name: '極地海岸',
    en: 'Polar Coast',
    image: './public/images/polar.webp',
    description: '寒冷海岸與浮冰連結陸地和海洋，提供覓食與繁殖的重要場所。',
  },
];
